### ISSUE TITLE
Bump up this version to 1.1.0-preview1

### ISSUE THREAD

**Issue by yukozh** [PomeloFoundation/Pomelo.JsonObject#3]

**Comment by caleblloyd** [comment]
Bumped in https://github.com/PomeloFoundation/Pomelo.JsonObject/commit/3d9ae19707e64ca7a37e596c6d541b7b2af8d04d

I don't want to publish a build for 1.1.0-preview1 yet though.  I think I will need to change this to cast to/from `byte[]` instead of `string` once https://github.com/mysql-net/MySqlConnector/issues/123 is implemented

**Comment by yukozh** [comment]
@caleblloyd Need push this to NuGet gallery.

**Comment by caleblloyd** [comment]
Pushed `1.0.0` and `1.1.0-prerelease10000` to https://www.nuget.org/packages/Pomelo.JsonObject/
